services:
  - type: web
    name: lensify-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=$PORT
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.5"
      - key: CORS_ORIGINS
        value: "http://localhost:5173,http://localhost:5174"
